package com.example.assignment1;

import java.util.ArrayList;

public class ProductDefaults {

    public static ArrayList<Product> getDefaults() {
        ArrayList<Product> list = new ArrayList<>();
        list.add(new Product("36", "Dock 8", "Accessory", 115.19, 4, "New", "seller1", false, false));
        list.add(new Product("37", "Call of Duty 6", "Game", 118.22, 5, "Used", "gameHub", true, false));
        list.add(new Product("38", "Remote 6", "Accessory", 377.64, 5, "Used", "admin", false, false));
        list.add(new Product("39", "PS4 1", "Console", 159.64, 2, "New", "gameHub", false, false));
        list.add(new Product("40", "PS Classic 7", "Console", 209.74, 2, "New", "seller1", true, false));
        list.add(new Product("41", "Camera 8", "Accessory", 283.98, 4, "Used", "gameHub", false, true));
        list.add(new Product("42", "Headset 4", "Accessory", 458.25, 1, "Used", "seller1", false, true));
        list.add(new Product("43", "GTA 1", "Game", 240.58, 9, "New", "gameHub", false, true));
        list.add(new Product("44", "Call of Duty 3", "Game", 437.2, 7, "Used", "storeX", true, false));
        list.add(new Product("45", "Uncharted 9", "Game", 419.01, 8, "New", "storeX", true, false));
        list.add(new Product("46", "Assassin’s Creed 4", "Game", 43.02, 1, "New", "gameHub", false, false));
        list.add(new Product("47", "Hard Drive 7", "Accessory", 428.01, 2, "Used", "storeX", true, false));
        list.add(new Product("48", "PS4 8", "Console", 283.21, 7, "Used", "admin", true, false));
        list.add(new Product("49", "Hard Drive 9", "Accessory", 350.21, 7, "Used", "admin", true, true));
        list.add(new Product("50", "Headset 7", "Accessory", 291.93, 2, "New", "gameHub", true, true));
        list.add(new Product("51", "Assassin’s Creed 9", "Game", 59.68, 2, "Used", "admin", false, false));
        list.add(new Product("52", "Controller 7", "Accessory", 476.69, 2, "Used", "storeX", true, false));
        list.add(new Product("53", "PS4 4", "Console", 91.08, 7, "New", "admin", true, false));
        list.add(new Product("54", "Assassin’s Creed 1", "Game", 279.44, 9, "New", "storeX", false, true));
        list.add(new Product("55", "PS5 2", "Console", 475.73, 9, "New", "admin", true, false));
        list.add(new Product("56", "Assassin’s Creed 9", "Game", 461.0, 2, "New", "storeX", true, false));
        list.add(new Product("57", "NBA 10", "Game", 217.91, 10, "Used", "admin", true, true));
        list.add(new Product("58", "PS Vita 3", "Console", 199.48, 1, "Used", "storeX", true, true));
        list.add(new Product("59", "God of War 8", "Game", 110.57, 4, "New", "seller1", true, true));
        list.add(new Product("60", "PS3 5", "Console", 92.01, 1, "New", "admin", false, false));
        list.add(new Product("61", "Controller 6", "Accessory", 198.3, 3, "Used", "gameHub", false, true));
        list.add(new Product("62", "Red Dead 8", "Game", 247.2, 8, "Used", "storeX", true, true));
        list.add(new Product("63", "PS Classic 3", "Console", 355.46, 9, "New", "seller1", false, false));
        list.add(new Product("64", "Remote 9", "Accessory", 220.11, 10, "Used", "seller1", false, false));
        list.add(new Product("65", "PS4 9", "Console", 110.56, 7, "New", "seller1", true, false));
        list.add(new Product("66", "VR 5", "Accessory", 86.14, 1, "Used", "gameHub", false, false));
        list.add(new Product("67", "VR 8", "Accessory", 236.15, 1, "New", "admin", false, false));
        list.add(new Product("68", "FIFA 8", "Game", 298.36, 10, "New", "gameHub", true, true));
        list.add(new Product("69", "NBA 2", "Game", 122.51, 8, "New", "storeX", true, true));
        list.add(new Product("70", "GTA 4", "Game", 404.82, 10, "Used", "storeX", true, true));
        list.add(new Product("71", "Spider-Man 6", "Game", 428.44, 4, "Used", "storeX", true, false));
        list.add(new Product("72", "FIFA 4", "Game", 201.2, 5, "New", "seller1", true, false));
        list.add(new Product("73", "PS3 5", "Console", 65.57, 4, "New", "seller1", true, false));
        list.add(new Product("74", "PS3 2", "Console", 286.4, 4, "New", "seller1", true, true));
        list.add(new Product("75", "FIFA 3", "Game", 27.32, 10, "Used", "seller1", false, true));
        list.add(new Product("76", "PS4 2", "Console", 372.61, 3, "New", "seller1", true, true));
        list.add(new Product("77", "PS Vita 2", "Console", 152.12, 6, "Used", "admin", false, true));
        list.add(new Product("78", "VR 5", "Accessory", 382.34, 5, "New", "seller1", false, false));
        list.add(new Product("79", "PS4 2", "Console", 191.58, 3, "Used", "admin", false, false));
        list.add(new Product("80", "PS5 10", "Console", 10.58, 10, "Used", "admin", false, false));
        list.add(new Product("81", "Red Dead 2", "Game", 179.36, 3, "Used", "gameHub", true, true));
        list.add(new Product("82", "PS3 2", "Console", 16.1, 8, "Used", "admin", true, true));
        list.add(new Product("83", "Call of Duty 2", "Game", 65.93, 10, "New", "storeX", false, false));
        list.add(new Product("84", "PS3 10", "Console", 235.71, 9, "Used", "gameHub", false, false));
        list.add(new Product("85", "Hard Drive 9", "Accessory", 318.99, 10, "New", "gameHub", true, true));
        list.add(new Product("86", "VR 5", "Accessory", 194.06, 8, "Used", "gameHub", true, true));
        list.add(new Product("87", "PS Vita 9", "Console", 343.67, 3, "Used", "gameHub", false, false));
        list.add(new Product("88", "Call of Duty 10", "Game", 203.6, 7, "Used", "gameHub", true, true));
        list.add(new Product("89", "Remote 4", "Accessory", 466.17, 5, "Used", "seller1", false, true));
        list.add(new Product("90", "God of War 2", "Game", 335.1, 8, "Used", "seller1", false, false));
        list.add(new Product("91", "Spider-Man 4", "Game", 342.14, 9, "Used", "admin", true, true));
        list.add(new Product("92", "Uncharted 3", "Game", 365.58, 10, "New", "gameHub", false, true));
        list.add(new Product("93", "Assassin’s Creed 4", "Game", 54.14, 5, "New", "admin", true, false));
        list.add(new Product("94", "PS5 8", "Console", 496.68, 9, "Used", "gameHub", false, true));
        list.add(new Product("95", "Headset 4", "Accessory", 449.71, 7, "Used", "storeX", true, true));
        list.add(new Product("96", "PS3 4", "Console", 99.27, 6, "New", "gameHub", false, false));
        list.add(new Product("97", "PS Classic 5", "Console", 125.2, 10, "New", "storeX", false, true));
        list.add(new Product("98", "NBA 9", "Game", 39.69, 7, "Used", "storeX", false, true));
        list.add(new Product("99", "Assassin’s Creed 5", "Game", 150.17, 10, "New", "gameHub", false, true));
        list.add(new Product("100", "NBA 1", "Game", 23.04, 6, "Used", "admin", false, false));
        list.add(new Product("101", "Uncharted 9", "Game", 11.22, 10, "Used", "seller1", false, true));
        list.add(new Product("102", "PS5 8", "Console", 35.51, 10, "Used", "gameHub", true, true));
        list.add(new Product("103", "FIFA 8", "Game", 430.66, 1, "Used", "storeX", false, true));
        list.add(new Product("104", "Controller 7", "Accessory", 109.93, 6, "New", "seller1", false, false));
        list.add(new Product("105", "Remote 3", "Accessory", 213.76, 1, "New", "storeX", true, true));
        list.add(new Product("106", "PS3 8", "Console", 237.44, 6, "New", "seller1", false, true));
        list.add(new Product("107", "VR 5", "Accessory", 449.91, 9, "Used", "seller1", false, true));
        list.add(new Product("108", "Controller 8", "Accessory", 431.46, 6, "New", "seller1", false, true));
        list.add(new Product("109", "GTA 8", "Game", 135.66, 3, "New", "storeX", true, true));
        list.add(new Product("110", "Hard Drive 5", "Accessory", 498.68, 9, "Used", "gameHub", true, true));
        list.add(new Product("111", "Dock 5", "Accessory", 411.62, 9, "Used", "storeX", true, true));
        list.add(new Product("112", "Controller 7", "Accessory", 404.95, 6, "New", "storeX", true, true));
        list.add(new Product("113", "FIFA 7", "Game", 158.16, 7, "New", "seller1", true, true));
        list.add(new Product("114", "PS Vita 1", "Console", 337.27, 9, "New", "storeX", false, true));
        list.add(new Product("115", "Call of Duty 4", "Game", 85.04, 4, "New", "gameHub", true, false));
        list.add(new Product("116", "Red Dead 5", "Game", 391.27, 9, "Used", "gameHub", false, true));
        list.add(new Product("117", "Controller 5", "Accessory", 463.4, 1, "Used", "storeX", true, true));
        list.add(new Product("118", "NBA 3", "Game", 469.46, 6, "New", "seller1", true, true));
        list.add(new Product("119", "Assassin’s Creed 10", "Game", 290.29, 7, "Used", "gameHub", false, true));
        list.add(new Product("120", "PS Vita 10", "Console", 141.95, 8, "Used", "seller1", false, false));
        list.add(new Product("121", "NBA 5", "Game", 126.18, 4, "Used", "gameHub", false, false));
        list.add(new Product("122", "Dock 2", "Accessory", 380.98, 9, "New", "seller1", true, false));
        list.add(new Product("123", "FIFA 3", "Game", 343.24, 10, "Used", "storeX", false, false));
        list.add(new Product("124", "GTA 8", "Game", 470.29, 4, "New", "admin", true, false));
        list.add(new Product("125", "God of War 8", "Game", 479.04, 8, "Used", "seller1", false, false));
        list.add(new Product("126", "Controller 4", "Accessory", 146.71, 8, "Used", "admin", false, false));
        list.add(new Product("127", "Camera 2", "Accessory", 453.21, 10, "Used", "storeX", false, true));
        list.add(new Product("128", "Controller 6", "Accessory", 307.03, 2, "Used", "gameHub", false, false));
        list.add(new Product("129", "PS4 5", "Console", 175.28, 10, "Used", "storeX", false, true));
        list.add(new Product("130", "Spider-Man 8", "Game", 494.71, 9, "New", "seller1", false, true));
        list.add(new Product("131", "PS Classic 5", "Console", 214.43, 8, "New", "gameHub", false, false));
        list.add(new Product("132", "Camera 7", "Accessory", 443.08, 5, "Used", "gameHub", false, false));
        list.add(new Product("133", "Hard Drive 4", "Accessory", 349.14, 4, "New", "gameHub", true, true));
        list.add(new Product("134", "PS5 5", "Console", 385.48, 10, "New", "gameHub", true, false));
        list.add(new Product("135", "Camera 5", "Accessory", 110.96, 3, "New", "admin", true, false));
        list.add(new Product("136", "Uncharted 4", "Game", 188.17, 10, "Used", "seller1", true, true));
        list.add(new Product("137", "Spider-Man 8", "Game", 298.72, 4, "New", "gameHub", true, true));
        list.add(new Product("138", "Headset 7", "Accessory", 260.06, 8, "Used", "storeX", true, true));
        list.add(new Product("139", "PS Vita 9", "Console", 23.34, 10, "Used", "admin", true, false));
        list.add(new Product("140", "Assassin’s Creed 3", "Game", 417.59, 1, "New", "seller1", false, true));
        list.add(new Product("141", "VR 6", "Accessory", 28.0, 4, "Used", "admin", false, true));
        list.add(new Product("142", "PS4 9", "Console", 182.28, 10, "New", "storeX", true, true));
        list.add(new Product("143", "PS3 5", "Console", 133.9, 5, "Used", "seller1", false, true));
        list.add(new Product("144", "Call of Duty 4", "Game", 396.48, 3, "New", "seller1", true, false));
        list.add(new Product("145", "Dock 2", "Accessory", 384.57, 9, "Used", "gameHub", false, false));
        list.add(new Product("146", "Spider-Man 1", "Game", 173.74, 8, "Used", "storeX", true, false));
        list.add(new Product("147", "Spider-Man 5", "Game", 290.92, 1, "New", "seller1", false, false));
        list.add(new Product("148", "VR 5", "Accessory", 163.83, 3, "Used", "storeX", true, false));
        list.add(new Product("149", "PS Vita 1", "Console", 432.52, 4, "New", "gameHub", false, false));
        list.add(new Product("150", "Assassin’s Creed 4", "Game", 153.92, 8, "Used", "admin", false, false));
        list.add(new Product("151", "Spider-Man 4", "Game", 172.07, 8, "Used", "gameHub", true, true));
        list.add(new Product("152", "VR 6", "Accessory", 309.74, 8, "New", "admin", false, false));
        list.add(new Product("153", "Dock 3", "Accessory", 369.24, 6, "Used", "gameHub", false, false));
        list.add(new Product("154", "PS4 5", "Console", 169.2, 2, "New", "gameHub", true, false));
        list.add(new Product("155", "Spider-Man 7", "Game", 281.41, 2, "New", "storeX", true, true));
        list.add(new Product("156", "Call of Duty 8", "Game", 141.95, 8, "New", "gameHub", true, false));
        list.add(new Product("157", "PS Classic 10", "Console", 397.05, 7, "Used", "gameHub", false, true));
        list.add(new Product("158", "Spider-Man 8", "Game", 263.53, 4, "New", "seller1", true, false));
        list.add(new Product("159", "Headset 4", "Accessory", 172.93, 9, "Used", "storeX", true, false));
        list.add(new Product("160", "GTA 8", "Game", 370.69, 2, "New", "gameHub", false, true));
        list.add(new Product("161", "Camera 8", "Accessory", 411.78, 2, "New", "admin", true, true));
        list.add(new Product("162", "NBA 9", "Game", 440.57, 6, "Used", "storeX", false, false));
        list.add(new Product("163", "PS Vita 5", "Console", 479.29, 3, "Used", "gameHub", false, true));
        list.add(new Product("164", "Camera 3", "Accessory", 83.39, 8, "Used", "gameHub", true, false));
        list.add(new Product("165", "Headset 2", "Accessory", 13.71, 10, "Used", "gameHub", false, false));
        list.add(new Product("166", "PS4 9", "Console", 153.68, 9, "New", "seller1", true, true));
        list.add(new Product("167", "PS Vita 10", "Console", 455.97, 9, "New", "storeX", true, false));
        list.add(new Product("168", "PS Vita 8", "Console", 355.84, 6, "New", "admin", false, false));
        list.add(new Product("169", "PS Vita 3", "Console", 377.83, 3, "New", "seller1", false, false));
        list.add(new Product("170", "Controller 8", "Accessory", 372.89, 3, "New", "gameHub", false, false));
        list.add(new Product("171", "Headset 8", "Accessory", 221.08, 4, "New", "seller1", false, false));
        list.add(new Product("172", "PS Classic 8", "Console", 150.72, 1, "Used", "gameHub", true, false));
        list.add(new Product("173", "PS5 2", "Console", 359.36, 9, "New", "seller1", false, true));
        list.add(new Product("174", "Assassin’s Creed 2", "Game", 58.81, 2, "New", "gameHub", false, false));
        list.add(new Product("175", "PS4 8", "Console", 486.84, 2, "Used", "gameHub", false, false));
        list.add(new Product("176", "FIFA 10", "Game", 260.68, 9, "New", "storeX", false, true));
        list.add(new Product("177", "Dock 2", "Accessory", 275.88, 8, "Used", "gameHub", false, false));
        list.add(new Product("178", "FIFA 6", "Game", 39.53, 10, "New", "gameHub", false, true));
        list.add(new Product("179", "PS Classic 8", "Console", 119.44, 10, "Used", "admin", false, false));
        list.add(new Product("180", "Headset 8", "Accessory", 232.06, 2, "New", "gameHub", false, false));
        list.add(new Product("181", "PS3 10", "Console", 242.21, 1, "Used", "admin", true, false));
        list.add(new Product("182", "Assassin’s Creed 1", "Game", 22.66, 5, "Used", "admin", true, false));
        list.add(new Product("183", "Camera 8", "Accessory", 451.55, 10, "Used", "admin", true, false));
        list.add(new Product("184", "Call of Duty 3", "Game", 392.08, 4, "New", "gameHub", true, false));
        list.add(new Product("185", "FIFA 7", "Game", 262.63, 4, "New", "admin", false, false));
        list.add(new Product("186", "Camera 3", "Accessory", 263.38, 7, "New", "storeX", false, true));
        list.add(new Product("187", "Remote 2", "Accessory", 117.49, 1, "Used", "seller1", false, false));
        list.add(new Product("188", "Camera 1", "Accessory", 381.77, 10, "New", "gameHub", false, true));
        list.add(new Product("189", "God of War 2", "Game", 471.06, 3, "New", "storeX", true, false));
        list.add(new Product("190", "VR 2", "Accessory", 312.91, 3, "New", "storeX", true, false));
        list.add(new Product("191", "Remote 10", "Accessory", 314.65, 2, "Used", "admin", true, true));
        list.add(new Product("192", "Dock 7", "Accessory", 55.13, 7, "New", "storeX", true, false));
        list.add(new Product("193", "Controller 9", "Accessory", 26.11, 2, "New", "admin", false, true));
        list.add(new Product("194", "Headset 6", "Accessory", 487.91, 10, "New", "storeX", true, true));
        list.add(new Product("195", "Remote 7", "Accessory", 131.12, 10, "Used", "gameHub", true, false));
        list.add(new Product("196", "Spider-Man 10", "Game", 67.12, 5, "New", "gameHub", true, true));
        list.add(new Product("197", "Remote 5", "Accessory", 75.4, 2, "New", "admin", false, false));
        list.add(new Product("198", "Spider-Man 9", "Game", 99.97, 10, "New", "admin", false, true));
        list.add(new Product("199", "Remote 8", "Accessory", 481.68, 6, "Used", "seller1", false, true));
        list.add(new Product("200", "Call of Duty 5", "Game", 392.52, 8, "New", "seller1", true, true));
        list.add(new Product("201", "Uncharted 5", "Game", 453.71, 8, "Used", "gameHub", false, false));
        list.add(new Product("202", "Spider-Man 9", "Game", 303.78, 9, "Used", "gameHub", false, false));
        list.add(new Product("203", "Hard Drive 5", "Accessory", 180.49, 6, "Used", "seller1", true, false));
        list.add(new Product("204", "PS Classic 5", "Console", 262.92, 5, "Used", "seller1", false, false));
        list.add(new Product("205", "PS Vita 7", "Console", 240.78, 9, "Used", "seller1", false, false));
        list.add(new Product("206", "FIFA 1", "Game", 129.65, 1, "Used", "storeX", false, false));
        list.add(new Product("207", "Headset 2", "Accessory", 279.58, 2, "New", "storeX", true, true));
        list.add(new Product("208", "Red Dead 6", "Game", 403.78, 10, "New", "seller1", false, false));
        list.add(new Product("209", "Assassin’s Creed 5", "Game", 343.21, 2, "Used", "gameHub", true, true));
        list.add(new Product("210", "God of War 4", "Game", 423.27, 4, "Used", "gameHub", true, false));
        list.add(new Product("211", "Spider-Man 2", "Game", 63.59, 8, "Used", "seller1", false, true));
        list.add(new Product("212", "VR 7", "Accessory", 303.74, 10, "Used", "admin", true, false));
        list.add(new Product("213", "Remote 2", "Accessory", 78.34, 8, "New", "gameHub", true, true));
        list.add(new Product("214", "Dock 7", "Accessory", 27.61, 3, "New", "gameHub", true, false));
        list.add(new Product("215", "Call of Duty 5", "Game", 444.45, 3, "Used", "storeX", false, false));
        list.add(new Product("216", "PS4 2", "Console", 396.68, 2, "New", "gameHub", false, false));
        list.add(new Product("217", "NBA 10", "Game", 481.39, 3, "New", "admin", true, false));
        list.add(new Product("218", "VR 10", "Accessory", 489.72, 8, "New", "admin", true, false));
        list.add(new Product("219", "PS4 10", "Console", 46.61, 6, "Used", "gameHub", false, true));
        list.add(new Product("220", "VR 5", "Accessory", 412.0, 9, "New", "admin", false, true));
        list.add(new Product("221", "FIFA 3", "Game", 240.9, 9, "New", "admin", true, true));
        list.add(new Product("222", "Remote 8", "Accessory", 123.78, 8, "Used", "gameHub", true, true));
        list.add(new Product("223", "PS5 2", "Console", 59.02, 5, "Used", "storeX", false, false));
        list.add(new Product("224", "PS Classic 10", "Console", 110.33, 4, "Used", "seller1", true, true));
        list.add(new Product("225", "Dock 9", "Accessory", 357.47, 4, "New", "seller1", true, false));
        list.add(new Product("226", "PS4 1", "Console", 370.3, 6, "Used", "gameHub", true, false));
        list.add(new Product("227", "NBA 1", "Game", 290.39, 10, "Used", "admin", true, true));
        list.add(new Product("228", "PS Vita 9", "Console", 167.62, 6, "Used", "seller1", true, false));
        list.add(new Product("229", "GTA 4", "Game", 407.62, 6, "New", "admin", true, false));
        list.add(new Product("230", "Dock 3", "Accessory", 276.58, 4, "New", "seller1", false, false));
        list.add(new Product("231", "PS Classic 9", "Console", 141.0, 3, "Used", "seller1", false, false));
        list.add(new Product("232", "PS5 7", "Console", 413.08, 10, "New", "gameHub", false, true));
        list.add(new Product("233", "Red Dead 8", "Game", 127.88, 6, "Used", "gameHub", false, false));
        list.add(new Product("234", "PS3 1", "Console", 31.41, 6, "Used", "storeX", true, false));
        list.add(new Product("235", "PS3 9", "Console", 135.4, 2, "Used", "storeX", true, false));

        return list;
    }
}
